/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
// use npx gltfjsx <path to glb file> to convert it to jsx file
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useSpring, a } from "@react-spring/three";

// Chest Sound
import chestOpenSound from "../../assets/sound/open-chest.mp3";
import closeChestSound from "../../assets/sound/close-chest.mp3";
const openChest = new Audio(chestOpenSound);
const closeChest = new Audio(closeChestSound);

export default function Model({ ...props }) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(
    "../../../coffre-minecraft.glb"
  );
  // Open functions
  const handleOpen = () => {
    props.setOpen(!props.open);
    openChest.volume = 0.3;
    closeChest.volume = 0.3;
    props.open ? openChest.play() : closeChest.play();
  };

  const openChestAnimation = useSpring({
    rotation: props.open ? [0, 0, 0] : [1.61, 0, 0],
    position: props.open ? [0, -1.5, 0] : [0, 0, 0],
  });
  return (
    <group onClick={handleOpen} ref={group} {...props} dispose={null}>
      {/* turns it to animated component and add rotation position to the whole model when clicked */}
      <a.group
        rotation={openChestAnimation.position}
        name="Armature"
        position={[0, -0.99, 0]}
      >
        <primitive object={nodes.Bone} />
        {/* Top half of the box, rotating it when clicked */}
        <a.primitive
          rotation={openChestAnimation.rotation}
          object={nodes.Bone001}
        />
        <skinnedMesh
          // added this prop to allow the mesh to cast shadows
          castShadow
          geometry={nodes.Cube.geometry}
          material={materials.Material}
          skeleton={nodes.Cube.skeleton}
        />
      </a.group>
    </group>
  );
}

useGLTF.preload("../../../coffre-minecraft.glb");
